DROP TABLE IF EXISTS gallery_items;
CREATE TABLE gallery_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  "imageUrl" TEXT NOT NULL,
  "affiliateUrl" TEXT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  userId INTEGER,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL
);

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  passwordHash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin', 'manager')),
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);